### ISSUE TITLE
Unable to require cljss.core

### ISSUE THREAD

**Issue by rafaelzlisboa** [roman01la/cljss#5] opened 2017-02-14 17:04 UTC
I generated a project with the re-frame template and tried to use cljss, but I'm unable to import it in the code, with this error:

```
No such namespace: cljss.core, could not locate cljss/core.cljs, cljss/core.cljc, or Closure namespace "cljss.core"
```

This is what the lein's `project.clj` deps look like now:

```clj
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.229"]
                 [reagent "0.6.0"]
                 [re-frame "0.9.1"]
                 [org.roman01la/cljss "0.1.0-SNAPSHOT"]
```

If I run `lein figwheel` and try to `(require '[cljss.core])` on the REPL it also doesn't seem to find the namespace.

--

I believe this happens because there is no `.cljs` file on the project, therefore compilation is probably ignoring the namespace. I added an `core.cljs`

```clj
(ns ^{:doc "Empty namespace, just so that the macros defined are picked up by the compiler"} cljss.core)
```

And that made it possible to require the namespace and use the macros on my code.

Could you take a look if that makes sense, or if there's something actually wrong with my env?

If you see that there's really something weird, take a look at my PR: https://github.com/roman01la/cljss/pull/4

**Comment by roman01la** [comment] 2017-02-14 20:46
Hi @rafaelzlisboa 

Not sure about this, but could you try to compile your project without figwheel and see if it fails?

**Comment by rafaelzlisboa** [comment] 2017-02-14 21:30
@roman01la yeap - just tried and same thing happened :(
`lein cljsbuild once` fails with a similar error:

```
Caused by: clojure.lang.ExceptionInfo: No such namespace: cljss.core, could not locate cljss/core.cljs, cljss/core.cljc, or Closure namespace "cljss.core" in file src/cljs/playground/views.cljs {:tag :cljs/analysis-error}
```

I also tried changing the clojure and clojurescript used to the same defined in cljss's `project.clj`

**Comment by roman01la** [comment] 2017-02-15 09:12
@rafaelzlisboa Thanks.

One more try: could you try to do it with `(:require-macros [cljss.core :refer [defstyles]])` ?

**Comment by rafaelzlisboa** [comment] 2017-02-15 12:54
@roman01la Good catch! It worked with `require-macros`.

**Comment by roman01la** [comment] 2017-02-15 13:31
Yeah, I had this issue when using with Figwheel. Not sure if it is a bug, but going to report.

**Comment by roman01la** [comment] 2017-02-15 14:41
@rafaelzlisboa apparently this is not an issue, but an expected behavior of the compiler

> roman01la [4:34 PM] 
does it mean that `:require-macros` explicitly tells compiler to look for  `clj` files, but with other forms of `require` compiler first requires `cljs`?

> dnolen [4:35 PM] 
yes that’s how it actually works

> [4:36]  
however in the case that `foo.cljs` `:require-macros` `foo.clj`

> [4:36]  
when users `:require` `foo.cljs`, we will automatically bring in the macros since they have the same namespace

I'm closing this issue. Thanks for your time!

**Closed by roman01la** 2017-02-15 14:41 UTC
